100-hours-a-week/16-Hot6-fe

ott/src/pages/Login.jsx

fix: redirect 함수 변경

---

ott/src/index.css

feat: 모바일 웹 최상단 스크롤 시 새로고침 설정

---

ott/src/App.jsx
ott/src/config/index.js
ott/src/pages/Login.jsx
ott/src/pages/OAuth2RedirectHandler.jsx
ott/src/store/authStore.js
ott/vite.config.js

feat: 로그인 JWT 저장

---

ott/src/api/client.js
ott/src/pages/Login.jsx

fix: 로그인 요청 url 변경 및 로그 작성

---

ott/src/App.jsx
ott/src/pages/Login.jsx
ott/src/pages/OAuth2RedirectHandler.jsx

fix: 브라우저단 리다이렉트

---

ott/src/App.jsx
ott/src/pages/OAuth2RedirectHandler.jsx

fix: 리다이렉트 후 accessToken 재발급

---

ott/src/pages/OAuth2RedirectHandler.jsx
ott/src/pages/PostEditor.jsx

fix: 리프레시 토큰 발급 요청 get -> post 변경

fix: get -> post 변경

---

ott/src/App.jsx
ott/src/pages/AiGenerationResult.jsx
ott/src/pages/OAuth2RedirectHandler.jsx
ott/vite.config.js

fix: post 3번째 매개변수로 쿠키 값 설정

---

ott/src/pages/OAuth2RedirectHandler.jsx
ott/src/store/authStore.js

refactor: 액세스 토큰 전역 관리 authStore.js로 옮기기

refactor: 액세스 토큰 전역 관리 authStore.js로 옮기기

---

ott/src/pages/DeskAI.jsx

fix: requestDto 이름과 맞게,formData 키 이름 맞추기

fix: requestDto 이름과 맞게,formData 키 이름 맞추기

---

ott/src/pages/OAuth2RedirectHandler.jsx
ott/src/store/authStore.js

chore: BASE_URL 미기입 오류 해결

---

ott/src/components/layout/BottomNavigation.jsx

chore: useNaviagte 선언 안됨

---

ott/src/pages/PostEditor.jsx

feat: 이미지 작성/수정 페이지

---

ott/src/components/common/ImageGenerationLoader.jsx
ott/src/pages/DeskAI.jsx

chore: 디버깅 로그 작성

---

ott/src/api/axios.js
ott/src/hooks/useDeskAICheck.js
ott/src/pages/Home.jsx

홈 화면에서 버튼 누를 시 Mixed-Content 에러 해결을 위한 디버깅 로그 추가

chore: 디버깅 로그 추가

---

ott/src/pages/DeskAI.jsx

fix: response.data.data 로 값 받는 것으로 해결

fix: response.data.data 로 값 받는 것으로 해결

---

ott/src/components/common/ImageGenerationLoader.jsx
ott/src/components/layout/RootLayout.jsx

fix: 로딩 스피너 및 토스트 메시지 max 768px로 변경

fix: 로딩 스피너 및 토스트 메시지 max 768px로 변경

---

ott/src/pages/AiGenerationResult.jsx

fix: 상품 이름 하단에 가격 표기로 변경 및 천 단위 콤마 표시

fix: 상품 이름 하단에 가격 표기로 변경 및 천 단위 콤마 표시

---

ott/src/pages/PostEditor.jsx

fix: 더미 데이터 제거 및 자유 카테고리 작성 API 적용

fix: 더미 데이터 제거 및 자유 카테고리 작성 API 적용

---

ott/src/pages/Posts.jsx

fix: 무한 스크롤 구현 및 작성 시간 포맷 함수 수정, 글쓰기 버튼 위치 변경

fix: 무한 스크롤 구현 및 작성 시간 포맷 함수 수정, 글쓰기 버튼 위치 변경

---

ott/src/App.jsx
ott/src/pages/MyPage.jsx

feat: 내 정보 조회(마이페이지) 생성

---

ott/src/pages/PostEditor.jsx

fix: ai 게시글 작성 JSON key 값 변경(ai_image_id)

fix: ai 게시글 작성 JSON key 값 변경(ai_image_id)

---

ott/src/components/common/ImageGenerationLoader.jsx

fix: 이미지 생성 조회 오류 해결

---

ott/src/components/common/ImageGenerationLoader.jsx

fix: 이미지 생성 완료 데이터 조회 수정

---

ott/src/components/common/ImageGenerationLoader.jsx
ott/src/pages/AiGenerationResult.jsx

fix: 이미지 생성 결과 게시글 작성 버튼 위치 변경 및 자신의 ai 생성 이미지 아닌 게시글 접근 불가

fix: 이미지 생성 결과 게시글 작성 버튼 위치 변경 및 자신의 ai 생성 이미지 아닌 게시글 접근 불가

---

ott/src/pages/AiGenerationResult.jsx

chore: 에러 로그 추가

---

ott/src/pages/AiGenerationResult.jsx

fix: 권한 없음 표시  모달 안뜸 해결

---

ott/src/pages/AiGenerationResult.jsx

fix: 모달 안뜸 해결

---

ott/src/pages/AiGenerationResult.jsx

style: 권한 없을 시 상단 Topbar style 변경

style: 권한 없을 시 상단 Topbar style 변경

---

ott/src/pages/PostEditor.jsx

fix: 로딩 스피너 무한 로딩 문제 해결

---

ott/src/pages/PostDetail.jsx

style: AI 게시글 이미지 스타일 변경

---

ott/src/pages/PostEditor.jsx

fix: 자유 게시판 form-data 잘못된 값 전달 오류 해결

fix: 자유 게시판 form-data 잘못된 값 전달 오류 해결

---

ott/src/pages/PostDetail.jsx

fix: 날짜 포맷 함수 변경 -> KST 적용

---

ott/src/components/common/CommentBottomSheet.jsx
ott/src/pages/PostDetail.jsx

style: 등록 문구 한 줄 차지

---

ott/src/components/common/CommentBottomSheet.jsx
ott/src/pages/PostDetail.jsx

chore: 댓글 UI 변경

---

ott/src/pages/PostDetail.jsx

fix: 댓글 목록 요청 api 해결

---

ott/src/pages/Posts.jsx

- merge할 브랜치의 위치를 확인해 주세요 (master/main ❌)
- 리뷰가 필요한 경우 'review' 라벨을 달아주고, 리뷰어를 지정해 주세요
- Approve된 PR은 리뷰어가 머지를 하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.
<br>
> 설명: fix: 게시글 조회에서 조회순, 좋아요순 조회 시 모든 데이터 반환되지 않음
> 설명: 각 조건에 맞게 게시글 조회되기 위해 lastLikeCount, lastViewCount 전달
> 설명: 게시글 조회 페이지에서 조건 별로 조회되는지 확인

fix: 게시글 조회 에러 해결

---

ott/src/pages/DeskAI.jsx

> 설명: 변경 동기와 내용(무엇을, 어떻게)을 상세히 기술합니다.
- 위치: 페이지 최상단, 업로드 박스 바로 위
- 문구:
- “당신의 책상 사진을 올리면 AI가 최적의 데스크셋업을 추천해드려요”
- 플레이스홀더
```
책상 전체가 잘 보이도록 사진을 올려주세요
• 실물 책상 or 원하는 스타일 예시
```
- 파일 형식: JPG, PNG (최대 5MB)
- 책상 전면과 주변 소품이 모두 보이게 촬영해주세요
> 설명: UI 변경이 있는 경우, 시각적 확인을 위해 캡처나 짧은 영상 첨부

feat: 이미지 생성 안내 문구 추가

---

.github/workflows/build-prod.yml
.github/workflows/deploy-dev.yml

* dev의 경우 이전과 똑같이 배포됩니다.
* prod(main)의 경우 push만으로는 트리거가 현재 없고(추후 테스트 과정 추가 가능), 태그 push 시 릴리즈됩니다.

main/dev 배포 로직 분리

---

ott/src/hooks/useDeskAICheck.js
ott/src/pages/DeskAI.jsx
ott/src/pages/Home.jsx

- merge할 브랜치의 위치를 확인해 주세요 (master/main ❌)
- 리뷰가 필요한 경우 'review' 라벨을 달아주고, 리뷰어를 지정해 주세요
- Approve된 PR은 리뷰어가 머지를 하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.
<br>
: 메인페이지에서 확인했던 토큰 검사를 이미지 업로드 페이지에서 진행
- 이미지 업로드 페이지에서 해당 사용자의 남은 이미지 생성 토큰을 출력하여 UX를 향상시키기 위해
- 이미지 업로드 페이지에서 토큰 검사를 하여 생성 요청을 막기 위해
> 설명: 기능이 잘 동작하는지 로컬에서 확인할 수 있는 절차를 기술합니다.
<!--
예시:
1. yarn dev로 서버 실행  
2. localhost:3000에서 데스크테리어 생성 버튼 클릭

feat: AI 이미지 토큰 값 출력 및 버튼 비활성화

---

ott/src/pages/DeskAI.jsx

- merge할 브랜치의 위치를 확인해 주세요 (master/main ❌)
- 리뷰가 필요한 경우 'review' 라벨을 달아주고, 리뷰어를 지정해 주세요
- Approve된 PR은 리뷰어가 머지를 하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.
<br>
- 불필요한 함수 제거
1. `yarn dev`로 서버 실행  
2. 메인 페이지에서 데스크테리어 생성 버튼 클릭

fix: 이미지 토큰 검사 로직 수정

---

ott/src/pages/DeskAI.jsx

- merge할 브랜치의 위치를 확인해 주세요 (master/main ❌)
- 리뷰가 필요한 경우 'review' 라벨을 달아주고, 리뷰어를 지정해 주세요
- Approve된 PR은 리뷰어가 머지를 하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.
<br>
- 이미지 생성 가능 토큰이 없다면, 이미지를 업로드 해도 버튼이 비활성화 되어야 한다.
> 설명: 기능이 잘 동작하는지 로컬에서 확인할 수 있는 절차를 기술합니다.
<!--
예시:
1. `yarn dev`로 서버 실행  
2. 이미지 업로드 페이지에서 이미지 업로드 후 버튼 상태 확인

fix: 이미지 생성 가능 토큰 0이면, 이미지 생성 버튼 비활성화

---

ott/src/pages/Order.jsx

- 주문하기 버튼 클릭 후 이동되는 페이지 (주문 생성 완료) 개발
- 결제 전 상태로, 중복 결제 및 주문 방지 처리
- 할인 상태의 스냅샷 저장

feat: 주문 생성 UI 개발

---

ott/src/config/index.js

fix: dev BASE_URL 재설정

---

ott/src/pages/OrderList.jsx

> 설명: fix: 주문 목록 조회 페이지 개선(페이지네이션)
- 주문 내역 조회 무한 스크롤 적용
- 5개 단위로 주문 내역 최신순 조회

fix: 주문 목록 조회 페이지 개선(페이지네이션)

---

ott/src/App.jsx
ott/src/pages/MyPage.jsx
ott/src/pages/PointHistory.jsx

- 포인트 내역 조회 UI 개발
- 적립 및 차감을 판단하여 +, - 및 색상 구분
- 적립 및 차감 이유를 판단하여 사유 출력
- 무한 스크롤 기법 적용

feat: 포인트 내역 조회 UI 개발

---

ott/src/components/layout/Header.jsx
ott/src/pages/MyPage.jsx
ott/src/pages/ProfileEdit.jsx

- 카테부 회원 추천인 코드 입력 UI 개발
- 유효한 코드 입력할 경우 is_verified 및 nicknameKakao 변경
- 카테부 회원만 상품 구매를 가능하도록 하기 위한 목적
- 회원 정보 변경에서 nicknameKakao 변경 가능

feat: 추천인 코드 입력 UI 개발

---

ott/src/App.jsx
ott/src/pages/MyPage.jsx
ott/src/pages/MyPosts.jsx

- 나의 게시글 조회 페이지 개발
- 자신이 작성한 게시글 10개 단위로 조회
- 무한 스크롤 적용

feat: 나의 게시글 조회 페이지 UI 개발

---

ott/src/pages/MyDeskImages.jsx

- 나의 데스크 보기 페이지 UI 개발
- 오늘, 어제, d일전, w주 전, mm달 전, yy년 전으로 관리
- 10개 단위로 조회
- 무한 스크롤 적용

feat: 나의 데스크 보기 페이지 UI 개발

---

ott/src/pages/OrderDetail.jsx

- 응답 dto 변경
- 기존 정상가, 할인금액, 최종가 등에 대해서 분리시키지 않은 상태
- 수정 후 해당 부분 분리 후 주문 상세 페이지 관리
- 조건에 따른 분기 처리 변경(환불 정보)

feat: 응답 dto 변경 및 화면 설계 변경

---

ott/src/pages/AiGenerationResult.jsx

- 기존 : AI 이미지 결과 페이지 조회 시 리스트로 한번에 추천 제품 조회
- 수정 : 생성된 이미지 상에서 관련된 제품들을 분류하여 해당 제품 위에 존재하는 버튼 클릭 시 관련 상품 리스트 조회

feat: AI 이미지 조회 시 좌표에 따라 상품 조회 기능 추가

---

ott/src/App.jsx
ott/src/pages/Home.jsx
ott/src/pages/RecommendedProductDetail.jsx
ott/src/pages/RecommendedProducts.jsx

- 데스크 이미지 기반 추천 제품 목록 및 상세 조회 페이지 개발

feat: 데스크 추천 제품 목록 및 상세 페이지 개발

---

ott/src/components/layout/BottomNavigation.jsx
ott/src/pages/MyPage.jsx
ott/src/pages/MyScrap.jsx

- 나의 스크랩 조회 페이지에서 추천 제품 상세 페이지 이동 추가

feat: 나의 스크랩 조회에서 추천 제품 페이지 이동 추가

---

ott/src/components/common/ImageGenerationLoader.jsx
ott/src/pages/DeskAI.jsx

- 이미지 생성 성공 모달 닫기 버튼 추가
- 이미지 생성 403 예외 대응

feat: 이미지 생성 모달 닫기 버튼 추가

---

ott/src/pages/Order.jsx
ott/src/pages/OrderDetail.jsx
ott/src/pages/OrderList.jsx

feat: order 페이지 변경

---

ott/src/App.jsx

fix: import 주석 오류 해결

---

ott/src/App.jsx
ott/src/pages/ProductDetail.jsx

> 설명: 변경 동기와 내용(무엇을, 어떻게)을 상세히 기술합니다.
이번 PR은 상품 상세 정보를 조회하는 페이지를 설계했습니다.
- 상품 옵션 선택 가능

121-product-detail

---

ott/src/App.jsx
ott/src/components/common/TopBar.jsx
ott/src/pages/MyScrap.jsx
ott/src/pages/OrderDetail.jsx
ott/src/pages/OrderList.jsx
ott/src/pages/Payment.jsx
ott/src/pages/ProductDetail.jsx
ott/src/pages/RecommendedProductDetail.jsx
ott/src/pages/RecommendedProducts.jsx

122-payment

---

ott/src/pages/OrderDetail.jsx

feat: 주문 취소 및 환불 사유 전송

---

ott/src/pages/OrderDetail.jsx

feat: 환불 및 취소에 대한 내역 설정

---

ott/src/pages/DeskAI.jsx

- 이미지 생성 페이지에서 기본, 카툰 컨셉 이미지 생성 가능

feat: 이미지 생성 컨셉 추가

---

ott/src/api/axios.js
ott/src/components/common/SimpleModal.jsx
ott/src/components/layout/Header.jsx
ott/src/pages/DeskAI.jsx
ott/src/pages/MyDeskImages.jsx
ott/src/pages/MyPage.jsx
ott/src/pages/MyPosts.jsx
ott/src/pages/MyScrap.jsx
ott/src/pages/OrderList.jsx
ott/src/pages/PointHistory.jsx
ott/src/pages/ProductDetail.jsx

> 설명: PR의 핵심 변경 사항을 간결하게 요약합니다.

fix: 전체 UI 및 모달 등

---

ott/src/components/common/LoginModal.jsx
ott/src/components/common/SimpleModal.jsx
ott/src/components/common/TopBar.jsx
ott/src/pages/AiGenerationResult.jsx
ott/src/pages/DeskAI.jsx
ott/src/pages/MyDeskImages.jsx
ott/src/pages/MyPage.jsx
ott/src/pages/OrderDetail.jsx
ott/src/pages/OrderList.jsx
ott/src/pages/Payment.jsx
ott/src/pages/PostEditor.jsx
ott/src/pages/ProductDetail.jsx
ott/src/pages/ProfileEdit.jsx

fix: 전체 QA 반영

---

ott/src/App.jsx
ott/src/components/common/Toast.jsx
ott/src/pages/MyDeskImages.jsx
ott/src/pages/MyScrap.jsx
ott/src/pages/PointHistory.jsx
ott/src/pages/ProductDetail.jsx
ott/src/pages/Products.jsx
ott/src/pages/ProfileEdit.jsx

fix: 패딩 설정, 스크랩 요청 변경, 목록, 상세 조회 진입 변경

---

ott/src/pages/Home.jsx

fix: 메인에서 더미 데이터 제거

---

ott/src/pages/MyPosts.jsx
ott/src/pages/PostDetail.jsx
ott/src/pages/Posts.jsx

fix: Time 설정값 변경

---

ott/src/components/common/LoginModal.jsx
ott/src/config/index.js
ott/src/pages/DeskAI.jsx
ott/src/pages/Login.jsx
ott/src/pages/OAuth2RedirectHandler.jsx
ott/src/store/authStore.js

- 로그인 후 활동하던 이전 페이지로 이동
- AI 이미지 생성 컨셉 추가(CARTOON)

291 feat/after login return page

---

ott/src/config/index.js

chore: base_url 오류

---

ott/package.json
ott/src/pages/ProductDetail.jsx
ott/tailwind.config.js
ott/yarn.lock

라이브러리 추가
- react-markdown
- @tailwindcss/typography

fix: 상품 상세 설명 마크다운 형태로 보여지기

---

ott/src/pages/MyPosts.jsx
ott/src/pages/Posts.jsx

> 설명: 변경 동기와 내용(무엇을, 어떻게)을 상세히 기술합니다.
- 게시글 작성자 이미지

fix: 프로필 이미지 오류 해결

---

ott/src/pages/MyPage.jsx

feat: 추천인 코드 -> 인증 코드로 변경

---

ott/src/components/common/CommentBottomSheet.jsx

fix: 댓글 날짜 포맷 오류 해결

---

ott/src/api/likes.js

- 좋아요 api POST, DELETE 메서드에서 POST로 통합

feat: 좋아요 api 통합

---

ott/src/api/scraps.js

- 스크랩 api POST, DELETE 메서드에서 POST로 통합

feat: scrap api 통합
